name: Deploy nsyte
on:
  push:
    branches:
      - main

concurrency:
  group: nsyte-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Deploy nsyte
        run: nsyte deploy dist/client --sec ${{ secrets.NBUNK_SECRET }}
